#!/bin/bash

#	This file gets fired on every boot of the system.	#

#	TODO:							#
#		• WHAT NETWORK?? (en0 oder en1)			#
#		• AUTOSTART OF NETWORK??? (wifi on/off)		#


 
# change MAC for ETHER randomly:
sudo ifconfig en0 ether $(openssl rand -hex 6 | sed 's%\(..\)%\1:%g; s%.$%%')

# change MAC for WIFI randomly:
sudo ifconfig en1 ether $(openssl rand -hex 6 | sed 's%\(..\)%\1:%g; s%.$%%')

# wifi needs a reset:
sudo airport -z

# take down wifi connection:
networksetup -setairportpower en1 off

# and up again:
networksetup -setairportpower en1 on




