#!/bin/bash

#	This script is for a timed alert		#
#							#
#	You don´t want to forget to take the pizza 	#
#	out of the oven in  half an hour?		#
#							#
#	Then this script helps you remember:		#
#							#
#	type: alertMe 30 "Pizza is ready!"		#
#	and concentrate back again on your work...	#


# test for arguments:
if [ $# -lt 1 ]
then
  echo " "
  echo "$0 error:  You must provide a timeperiod in minutes and a message (optional)"
  echo " "
  echo "           usage: $ alertMe [time in minutes] <message>"
  echo " "
  exit 1
fi


# get the message, if not provided set a default one
message="HEY! TIME IS UP!"
if [ $# = 2 ]
then
  message="$2"
fi


# The rest of the process runs in a subshell and gets detached from the shell jobs list:
#
# The () creating the subshell
#
# At the end "&>/dev/null &disown" :
# & -> detach command from stdin
# >/dev/null detaches the shell session from stdout and stderr
# &disown removes the command from the shell's job list

(
# convert minutes into seconds and wait this timespan:
t=$(expr $1 '*' 60)
sleep $t

# its time to activate the alert display:
wait
osascript -- - "$message" <<'EOF'
  on run(argv)
    return display alert argv
  end
EOF
) &>/dev/null &disown
