#!/bin/bash

#	A little script to change MAC and hostname randomly...		#
#									#
#	Use it as command in terminal or put it as sudo crontab -e	#
#	into your cronjoblist. Use @reboot if you want cron to fire	#
#	this file on every boot of the system.				#
#									#
#									#
#	2016 by d11th							#


#	TODO:								#
#		• implement user parameter like:			#
#			- choose network-connection (en0 or en1)	#
#			- decide whether you want to connect or not	#
#			- choose a name for host or computer		#
#									#
#		• implement name change with random names		#
#									#

#       WARNING! THIS IS UNTESTED! USE AT OWN RISK!        #

# 1)  First of all we have to make shure that the networkcards are on:

# wifi connection:
sW=$(ifconfig en1 | grep status)
if [[ "$sW" = "status: inactive" ]] then
  networksetup -setairportpower en1 on
fi

# ethernet connection:
sE=$(ifconfig en0 | grep status)
if [[ "$sE" = "status: inactive" ]] then
  sudo ifconfig en0 up
fi



# 2)  Then we change computername an MAC:

# change computer name (on my computer only  the ComputerName is relevant, but to be sure change LocalHostName too):
sudo scutil --set ComputerName "MrIncognito"
sudo scutil --set LocalHostName "MrIncognito"
 
# change MAC for ETHER randomly:
sudo ifconfig en0 ether $(openssl rand -hex 6 | sed 's%\(..\)%\1:%g; s%.$%%')

# change MAC for WIFI randomly:
sudo ifconfig en1 ether $(openssl rand -hex 6 | sed 's%\(..\)%\1:%g; s%.$%%')



# 3)  And now reset the connection and bring all up again:

# in order to broadcast the changed MAC on Wifi, the airportcard needs a reset:
sudo airport -z

# wifi
networksetup -setairportpower en1 off
networksetup -setairportpower en1 on

# ethernet
sudo ifconfig en0 down
sudo ifconfig en0 up


