#!/bin/bash

#	This file compares a SHA generated with shasum with a		#
#	give SHA from origin. This helps to easely check if the		#
#	provided download is not touched by third party...		#
#									#
#	Input:								#
#		1) path/to/file						#
#		2) original SHA						#
#		3) SHA-algorythm (e.g. 1, 256, ...)			#
#									#
#	2016 by d11th							#


# first check if all parameters are given by user:
if [ $# -lt 3 ]
then
 echo "$0 error: you must supply a file, its origin SHA and what sha-method! (So 3 arguments)"
 exit 1
fi

# calculate the shasum, then split the resulting string (we only need the first part):
spl='\ ' read -a arr <<< "$(shasum -a $3 $1)"

#echo "${#arr[@]}" # for debugging: print length of array #

# check if both strings are equal:
if [[ ${arr[0]} = "$2" ]]
then
 echo "OK !!"
else
 echo "WRONG!"
fi

# to manualy compare (never trust the programmer ;-):
echo "shasum: ${arr[0]}"
echo "origin: $2"

exit 0
